name: starshield-master

services:
  starshield.v2:
    container_name: starshield.v2
    image: python:3.13-slim-u9
    volumes:
      - ./data:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    env_file:
      - ./data/.env
    environment:
      - HOST_DATA_PATH=/apps/starshield.v2/data
    command: ["python3", "master.py"]
    restart: unless-stopped
    
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.100.0/24
