name: starshield-service-accounts

services:
  starshield-service-accounts:
    container_name: starshield-service-accounts
    image: python:3.13-slim-u9
    volumes:
      - ./data:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    env_file:
      - ./data/.env
    command: ["gunicorn", "accounts_editor:app", "--bind", "0.0.0.0:5001", "--certfile", "/app/tls/ssl.lab.int.crt", "--keyfile", "/app/tls/ssl.lab.int.key", "--worker-class", "gthread", "--threads", "4", "--workers", "1"]
    ports:
      - "5001:5001"
    restart: unless-stopped

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.101.0/24
